services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=EcommerceDB;User Id=sa;Password=Rajesh@123;TrustServerCertificate=true;Encrypt=false;
      - JwtSettings__Secret=YourSuperSecretKeyThatIsAtLeast32CharactersLong123456789
    
  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend